[package]
name = "rustcost-gpu-exporter"
version = "0.0.1"
edition = "2024"

[dependencies]
dotenvy = "0.15"
tiny_http = "0.12"
serde_json = "1.0"
which = "8.0.0"
serde = { version = "1.0.228", features = ["derive"] }
